# syntax=docker/dockerfile:1

FROM python:3.10.1-slim-buster

WORKDIR /twitter-scraper

COPY ./twitter-scraper/requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY ./twitter-scraper .

CMD [ "python3", "app.py"]